### ISSUE TITLE
Tighter webhook config

### ISSUE THREAD

**Issue by kfox1111** [rancher/externalip-webhook#10]
https://github.com/rancher/externalip-webhook/blob/master/chart/templates/admissionregistration.yaml#L19
Has failurePolicy: Ignore
It would be good if this was made a helm values so it could be be overridden to "Fail" so no requests go through if there is a problem with the webhook.

Also, when set to Fail, we would need a way to set restrictions on which namespaces the admission monitored. For example, we need to exclude the webhook's own service. Could the namespaceSelector property of the validatingwebhook be optionally set in the values file and toYaml'ed in so that it can be restricted to certain namespaces?

**Comment by cbron** [comment]
Hello @kfox1111 , thanks for your input, those would be good additions. But due to the new additions in k8s, this chart is now deprecated: https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#denyserviceexternalips
